#!/bin/sh
year="$1"
day="$2"
part="$3"

# Compile
cppPath="./${year}/${day}/day${day}p${part}.cpp"
script_dir="$(cd "$(dirname "$0")" && pwd)"

g++ "$script_dir/${year}/${day}/day${day}p${part}.cpp" -o "$script_dir/${year}/${day}/day${day}p${part}" -Wall --debug

#"$script_dir/$year/$day/day${day}p${part}"

(
    cd "$script_dir/$year/$day" || exit
    "./day${day}p${part}"
)

